/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apple_ii_computer.glb --transform 
Files: apple_ii_computer.glb [14.41MB] > C:\Users\Arthur Santana\Documents\GitHub\Nextjs-Creative-Portfolio-Starter-Code-Files\public\models\apple_ii_computer-transformed.glb [1.26MB] (91%)
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-ii-computer-b5d316548d634f16a72dd503db0aa01b
Title: Apple II Computer
*/

"use client"

import React, { useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function AppleII(props) {
  const { nodes, materials } = useGLTF('/models/apple_ii_computer-transformed.glb')

  const modelRef = useRef()

  useFrame((state, delta, xFrame) => {
    modelRef.current.position.y = -1 + 0.2 * Math.sin(state.clock.elapsedTime)
    modelRef.current.rotation.y = state.clock.elapsedTime * 0.4
  })

  return (
    <group {...props} 
    ref={modelRef}
    position={[0, -1.5,0]}
    scale={[8, 8, 8]}
    rotation={[0.25,0,0]}
    dispose={null}>
      <OrbitControls/>
      <mesh geometry={nodes.Object_4.geometry} material={materials.appleII_body_mat} position={[-0.059, 0.095, -0.025]} scale={0.138} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.appleII_details_mat} position={[-0.054, 0.021, 0.088]} scale={0.138} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.plugs_mat} position={[-0.05, 0.077, -0.006]} scale={0.138} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.appleII_keyboard_mat} position={[-0.114, 0.071, 0.235]} scale={0.138} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.cable_mat} position={[-0.062, -0.036, 0.022]} scale={0.138} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.diskII_mat} position={[0.247, 0.055, -0.068]} scale={0.138} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.monitor_base_mat} position={[-0.044, 0.203, -0.065]} scale={0.138} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Monitor_details_mat} position={[-0.087, 0.27, -0.165]} scale={0.138} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.monitor_screen_mat} position={[-0.087, 0.272, 0.006]} scale={0.138} />
    </group>
  )
}

useGLTF.preload('/models/apple_ii_computer-transformed.glb')
