import localFont from 'next/font/local';
import "./globals.css";
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

const appleGaramond = localFont({
  src: [
    {
      path: '../../public/fonts/apple-garamond/AppleGaramond.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/apple-garamond/AppleGaramond-Italic.woff',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/fonts/apple-garamond/AppleGaramond-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/apple-garamond/AppleGaramond-LightItalic.woff',
      weight: '300',
      style: 'italic',
    }
  ],
  variable: '--font-apple-garamond',
})

const chicagoFLF = localFont({src: '../../public/fonts/chicago/chicago.ttf', variable: '--font-chicagoFLF'}
  
)

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${chicagoFLF.className} ${appleGaramond.variable}`}>
        <Header />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
