/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apple_ii_computer.glb --transform 
Files: apple_ii_computer.glb [14.41MB] > C:\Users\Arthur Santana\Documents\GitHub\Nextjs-Creative-Portfolio-Starter-Code-Files\public\models\apple_ii_computer-transformed.glb [1.26MB] (91%)
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-ii-computer-b5d316548d634f16a72dd503db0aa01b
Title: Apple II Computer
*/

"use client"

import React, { useEffect, useRef } from 'react'
import { OrbitControls, ScrollControls, Stage, useGLTF, useScroll } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import gsap from 'gsap'

export default function Model({ source }) {


  const modelRef = useRef()
  const orbitControlsRef = useRef()
  const scroll = useScroll()
  const { camera } = useThree()

  const { scene } = useGLTF(source);

  useFrame(() => {

    const windowHeight = window.innerHeight;
    const fullHeight = document.documentElement.scrollHeight;
    const currentPosition = window.scrollY;

    const scrollPercentage = (currentPosition / (fullHeight - windowHeight)) * 100;

    const angle = scrollPercentage * 0.01;
    const radius = 3;

    camera.position.y += radius * Math.sin(angle * 0.02);

    if (scrollPercentage > 10) {
      if (scrollPercentage < 50) {
        camera.position.x -= radius * Math.sin(angle);
        camera.position.z -= radius * Math.cos(angle);
      } else {
        camera.position.x += radius * Math.sin(angle);
        camera.position.z += radius * Math.cos(angle);
      }
    }

    camera.lookAt(0, 0, 0); 

    if (orbitControlsRef.current) {
      orbitControlsRef.current.autoRotate = false;
    }
  })

  return (
    <group
      ref={modelRef}
      scale={[8, 8, 8]}
      dispose={null}>
      <OrbitControls
        ref={orbitControlsRef}
        enableZoom={false}
        enableRotate={false} 
      />
      <Stage preset="rembrandt" intensity={1} environment="city">
        <primitive object={scene} />
      </Stage>
    </group>
  )
}

useGLTF.preload('/models/apple_ii_computer-transformed.glb')