/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apple_ii_computer.glb --transform 
Files: apple_ii_computer.glb [14.41MB] > C:\Users\Arthur Santana\Documents\GitHub\Nextjs-Creative-Portfolio-Starter-Code-Files\public\models\apple_ii_computer-transformed.glb [1.26MB] (91%)
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-ii-computer-b5d316548d634f16a72dd503db0aa01b
Title: Apple II Computer
*/

"use client"

import React, { useRef } from 'react'
import { OrbitControls, Stage, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({source}) {

  const modelRef = useRef()

  const { scene } = useGLTF(source);

  return (
    <group
      ref={modelRef}
      scale={[8, 8, 8]}
      dispose={null}>
      <OrbitControls />
      <Stage preset="rembrandt" intensity={1} environment="city">
        <primitive object={scene} />
      </Stage>
    </group>
  )
}

useGLTF.preload('/models/apple_ii_computer-transformed.glb')
